// This file is automatically generated. Do not edit it directly.
// Auth middleware stub for SPA - the original used TanStack Start server middleware.
// In a plain SPA, authentication is handled client-side via the supabase client.
import type { Database } from './types';

export type { Database };

// Placeholder export to avoid import errors if referenced
export const requireSupabaseAuth = null;
